"""
test_controller.py

Author:  Nathan Filipowitz
Date:    2026-03-09
Purpose: Integration tests testing server behavior: file are showing, user cannot download other files by typing in URL, folder download generates zip.

"""


import pytest
import pytest_asyncio
import os
import shutil
import tempfile
from aiohttp import web
from pathlib import Path
from views import download_view

# AI USE: The logic behind integration testing strategy for this app was generated by AI, the idea of recreating the functions, 
# to 'Act' a browser_mock, to test only aiohttp features was out of my reach in terms of capabilities and experience. But the generated code was
# clearly understood and implemented with a minimalistic approach in mind. To make sure I understand everything that's going on.

# Recreate application functions because real ones depends on flet application 'page' argument (no flet app for testing)
async def handle_index_mock(request):
    shared_path = request.app['shared_path']
    files = os.listdir(shared_path)
    return web.Response(text=download_view.generate_html(files), content_type='text/html')

async def handle_download_mock(request):
    filename = request.match_info.get('filename')
    shared_path = request.app['shared_path']
    base_dir = Path(shared_path).resolve()
    requested_path = (base_dir / filename).resolve()

    # Protect against traversal attack requests
    if not str(requested_path).startswith(str(base_dir)):
        return web.Response(text="Access Denied", status=403)

    if requested_path.is_file():
        return web.FileResponse(requested_path)
    
    # make zip if requested file is a folder
    if requested_path.is_dir():
        with tempfile.NamedTemporaryFile(delete=False, suffix='.zip') as tmp:
            zip_path = shutil.make_archive(tmp.name.replace('.zip', ''), 'zip', requested_path)
            return web.FileResponse(zip_path)

    return web.Response(text="Not Found", status=404)


# Arrange
@pytest_asyncio.fixture
async def browser_mock(aiohttp_client, tmp_path):
    # Creates a directory
    mock_shared_directory = tmp_path / "shared"
    mock_shared_directory.mkdir()
    (mock_shared_directory / "test.txt").write_text("ceci est un test")
    subfolder_path = mock_shared_directory / "subfolder"
    subfolder_path.mkdir()
    (subfolder_path / "inner.txt").write_text("interne")

    # Create a minimalist aiohttp server implementing the mock features
    app = web.Application()
    app['shared_path'] = str(mock_shared_directory)
    app.router.add_get('/', handle_index_mock)
    app.router.add_get('/{filename}', handle_download_mock)
    return await aiohttp_client(app)